{% set name = "bilby.cython" %}
{% set version = "0.5.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bilby_cython-{{ version }}.tar.gz
  sha256: 44400b2abc6fa592b13d69f33460cb156d6edb48a783f5539ee0a21e1d0a3508

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  requires:
    - pip
    # requirements for testing
    - astropy-base  # [unix and python_impl == 'cpython']
    - pytest  # [unix and python_impl == 'cpython']
    - python-lal  # [unix and python_impl == 'cpython']
    - scipy  # [unix and python_impl == 'cpython']
    - attrs  # [unix and python_impl == 'cpython']
    - corner  # [unix and python_impl == 'cpython']
    - dill  # [unix and python_impl == 'cpython']
    - dynesty >=2.0.1  # [unix and python_impl == 'cpython']
    - emcee  # [unix and python_impl == 'cpython']
    - h5py  # [unix and python_impl == 'cpython']
    - matplotlib-base  # [unix and python_impl == 'cpython']
    - packaging  # [unix and python_impl == 'cpython']
    - pandas  # [unix and python_impl == 'cpython']
    - pytables  # [unix and python_impl == 'cpython']
    - tqdm  # [unix and python_impl == 'cpython']
  commands:
    # check metadata
    - python -m pip show bilby-cython
    # run test suite
    - python -m pip install bilby --no-deps  # [unix and python_impl == 'cpython']
    - python -m pytest -ra -v --pyargs bilby_cython.test -k "not longdouble and not float64"  # [unix and python_impl == 'cpython']

about:
  home: https://git.ligo.org/colm.talbot/bilby-cython
  summary: Optimized functionality for Bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
