{% set name = "bilby.cython" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bilby.cython-{{ version }}.tar.gz
  sha256: 7ca8e06f1fd8df46a06174491617d6fb369c61b70bab2ab39a1a84af47df79fc

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython>3                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
    # requirements for testing
    - astropy  # [unix and python_impl == 'cpython']
    - bilby  # [unix and python_impl == 'cpython']
    - pytest  # [unix and python_impl == 'cpython']
    - python-lal  # [unix and python_impl == 'cpython']
  commands:
    # check metadata
    - python -m pip show bilby-cython
    # run test suite
    - python -m pytest -ra -v --pyargs bilby_cython.test  # [unix and python_impl == 'cpython']

about:
  home: https://git.ligo.org/colm.talbot/bilby-cython
  summary: Optimized functionality for Bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
