{% set name = "bilby.cython" %}
{% set version = "0.5.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bilby_cython-{{ version }}.tar.gz
  sha256: 6ed083ad093420f91cb76bdd5cf85fc3950597b16d451d38987571ed8f9112a7

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  requires:
    - pip
    # requirements for testing
    - astropy-base  # [unix and python_impl == 'cpython']
    - bilby >= 2.4  # [unix and python_impl == 'cpython']
    - pytest  # [unix and python_impl == 'cpython']
    - python-lal  # [unix and python_impl == 'cpython']
  commands:
    # check metadata
    - python -m pip show bilby-cython
    # run test suite
    - python -m pytest -ra -v --pyargs bilby_cython.test -k "not longdouble and not float64"  # [unix and python_impl == 'cpython']

about:
  home: https://git.ligo.org/colm.talbot/bilby-cython
  summary: Optimized functionality for Bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
