{% set name = "bilby.cython" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bilby_cython-{{ version }}.tar.gz
  sha256: 44400b2abc6fa592b13d69f33460cb156d6edb48a783f5539ee0a21e1d0a3508

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                             # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  requires:
    - pip
    # requirements for testing
    - astropy  # [unix and python_impl == 'cpython']
    - bilby  # [unix and python_impl == 'cpython']
    - pytest  # [unix and python_impl == 'cpython']
    - python-lal  # [unix and python_impl == 'cpython']
  commands:
    # check metadata
    - python -m pip show bilby-cython
    # run test suite
    - python -m pytest -ra -v --pyargs bilby_cython.test -k "not longdouble and not float64"  # [unix and python_impl == 'cpython']

about:
  home: https://git.ligo.org/colm.talbot/bilby-cython
  summary: Optimized functionality for Bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
